chore(build): add docker-compose.prod.yml to server

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,10 +8,9 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-
     steps:
       - name: Check out the repo
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v1
@@ -34,6 +33,15 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     steps:
+      - name: Copy docker-compose.prod.yml to server
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ secrets.SERVER_IP }}
+          username: ${{ secrets.SERVER_USER }}
+          key: ${{ secrets.SSH_KEY }}
+          source: 'docker-compose.prod.yml'
+          target: '~/ryanjordan.dev'
+
       - name: Deploy to server
         uses: appleboy/ssh-action@master
         with:
@@ -42,5 +50,10 @@ jobs:
           key: ${{ secrets.SSH_KEY }}
           script: |
             cd ryanjordan.dev
-            docker compose -f docker-compose.prod.yml pull
-            docker compose -f docker-compose.prod.yml up -d
+            if [ -f docker-compose.prod.yml ]; then
+              docker compose -f docker-compose.prod.yml pull
+              docker compose -f docker-compose.prod.yml up -d
+            else
+              echo "docker-compose.prod.yml not found"
+              exit 1
+            fi
